import { remainApi } from '../../../api/remain'
import type {
  ConfirmRemainPriceRequest,
  CreateRemainRegistrationRequest,
  RemainAdjustmentCancelRequest,
  RemainAdjustmentCreateRequest,
  RemainAdjustmentNextSettlementRequest,
  RemainCreditRequest,
  RemainCreditReverseRequest,
  RemainInventoryQuery,
  RemainRefundCreateRequest,
  RemainRefundDecisionRequest,
  RemainSaleCreateRequest,
  RemainSaleReverseRequest,
  RemainRegistrationQuery,
  RollbackRemainRequest,
} from '../../../types/remain'

export const remainService = {
  registrations: (query: RemainRegistrationQuery) => remainApi.registrations(query),
  registration: (uuid: string) => remainApi.registration(uuid),
  createRegistration: (data: CreateRemainRegistrationRequest) => remainApi.createRegistration(data),
  confirmPrice: ({ uuid, data }: { uuid: string; data: ConfirmRemainPriceRequest }) => remainApi.confirmPrice(uuid, data),
  rollback: ({ uuid, data }: { uuid: string; data: RollbackRemainRequest }) => remainApi.rollback(uuid, data),
  inventory: (query: RemainInventoryQuery) => remainApi.inventory(query),
  adjustments: () => remainApi.adjustments(),
  adjustment: (uuid: string) => remainApi.adjustment(uuid),
  createAdjustment: ({ registrationUuid, data }: { registrationUuid: string; data: RemainAdjustmentCreateRequest }) => remainApi.createAdjustment(registrationUuid, data),
  cancelAdjustment: ({ uuid, data }: { uuid: string; data: RemainAdjustmentCancelRequest }) => remainApi.cancelAdjustment(uuid, data),
  bindNextSettlement: ({ uuid, data }: { uuid: string; data: RemainAdjustmentNextSettlementRequest }) => remainApi.bindNextSettlement(uuid, data),
  credit: ({ uuid, data }: { uuid: string; data: RemainCreditRequest }) => remainApi.credit(uuid, data),
  reverseCredit: ({ uuid, data }: { uuid: string; data: RemainCreditReverseRequest }) => remainApi.reverseCredit(uuid, data),
  refunds: () => remainApi.refunds(),
  refund: (uuid: string) => remainApi.refund(uuid),
  createRefund: ({ uuid, data }: { uuid: string; data: RemainRefundCreateRequest }) => remainApi.createRefund(uuid, data),
  approveRefund: ({ uuid, data }: { uuid: string; data: RemainRefundDecisionRequest }) => remainApi.approveRefund(uuid, data),
  payRefund: ({ uuid, data }: { uuid: string; data: RemainRefundDecisionRequest }) => remainApi.payRefund(uuid, data),
  cancelRefund: ({ uuid, data }: { uuid: string; data: RemainRefundDecisionRequest }) => remainApi.cancelRefund(uuid, data),
  sales: () => remainApi.sales(),
  createSale: (data: RemainSaleCreateRequest) => remainApi.createSale(data),
  reverseSale: ({ uuid, data }: { uuid: string; data: RemainSaleReverseRequest }) => remainApi.reverseSale(uuid, data),
}
