import {
  cancelReceivePayment,
  createSettleByMonth,
  createSettleByOrders,
  getSettleCandidates,
  getSettleOrderDetail,
  getSettleOrderHeader,
  getSettleDetails,
  getSettleReceives,
  getSettlePrintLines,
  getSettleOperationLogs,
  getSettleOrderList,
  getSettleOrderSummary,
  receivePayment,
  quoteSettleByMonth,
  quoteSettleByOrders,
  voidSettleOrder,
  getSettleDiscountApprovals,
  getLatestSettleDiscountApproval,
  getSettleDiscountApprovalPage,
  getSettleDiscountApprovalDetail,
  decideSettleDiscountApproval,
  requestSettleDiscountApproval,
  approveSettleDiscount,
  getSettleCollectionReminders,
  getSettleCollectionSummary,
  recordSettleCollectionReminder,
} from '../../../api/settle'
import type {
  ReceiveDTO,
  SettleActionReasonDTO,
  SettleByMonthDTO,
  SettleByOrdersDTO,
  SettleCandidateQuery,
  SettleQuery,
  SettleQuoteByOrdersDTO,
  SettleQuoteByMonthDTO,
  SettleDiscountApprovalRequestDTO,
  SettleDiscountApprovalQuery,
  SettleDiscountDecisionDTO,
  SettleCollectionReminderRequestDTO,
} from '../../../types/settle'

export const settleService = {
  candidates: (query: SettleCandidateQuery) => getSettleCandidates(query),
  quoteByMonth: (data: SettleQuoteByMonthDTO) => quoteSettleByMonth(data),
  quoteByOrders: (data: SettleQuoteByOrdersDTO) => quoteSettleByOrders(data),
  createByMonth: (data: SettleByMonthDTO) => createSettleByMonth(data),
  createByOrders: (data: SettleByOrdersDTO) => createSettleByOrders(data),
  detail: (uuid: string) => getSettleOrderDetail(uuid),
  detailHeader: (uuid: string) => getSettleOrderHeader(uuid),
  details: (uuid: string) => getSettleDetails(uuid),
  receives: (uuid: string) => getSettleReceives(uuid),
  printLines: (uuid: string) => getSettlePrintLines(uuid),
  operationLogs: (uuid: string) => getSettleOperationLogs(uuid),
  list: (query: SettleQuery) => getSettleOrderList(query),
  summary: (query: SettleQuery) => getSettleOrderSummary(query),
  collectionSummary: (query: SettleQuery) => getSettleCollectionSummary(query),
  collectionReminders: (uuid: string) => getSettleCollectionReminders(uuid),
  recordCollectionReminder: (params: { uuid: string; data: SettleCollectionReminderRequestDTO }) =>
    recordSettleCollectionReminder(params.uuid, params.data),
  receive: (params: { uuid: string; data: ReceiveDTO }) => receivePayment(params.uuid, params.data),
  discountApprovals: (uuid: string) => getSettleDiscountApprovals(uuid),
  latestDiscountApproval: (uuid: string) => getLatestSettleDiscountApproval(uuid),
  discountApprovalPage: (query: SettleDiscountApprovalQuery) => getSettleDiscountApprovalPage(query),
  discountApprovalDetail: (uuid: string) => getSettleDiscountApprovalDetail(uuid),
  decideDiscountApproval: (params: { uuid: string; action: 'approve' | 'reject' | 'cancel';
    data?: SettleDiscountDecisionDTO }) => decideSettleDiscountApproval(params.uuid, params.action, params.data),
  requestDiscountApproval: (params: { uuid: string; data: SettleDiscountApprovalRequestDTO }) =>
    requestSettleDiscountApproval(params.uuid, params.data),
  approveDiscount: (params: { uuid: string; approvalUuid: string }) =>
    approveSettleDiscount(params.uuid, params.approvalUuid),
  cancelReceive: (params: { uuid: string; receiveUuid: string; data: SettleActionReasonDTO }) =>
    cancelReceivePayment(params.uuid, params.receiveUuid, params.data),
  void: (params: { uuid: string; data: SettleActionReasonDTO }) => voidSettleOrder(params.uuid, params.data),
}
