package com.paper.mes.processorder.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import com.paper.mes.common.BaseEntity;
import com.paper.mes.processorder.model.ProcessRollDispositionAction;
import com.paper.mes.processorder.model.ProcessRollDispositionStatus;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.time.LocalDateTime;

/** Immutable business trail for a source roll leaving its issued order path. */
@Data
@EqualsAndHashCode(callSuper = true)
@TableName("biz_process_roll_disposition")
public class ProcessRollDisposition extends BaseEntity {
    @TableId(type = IdType.ASSIGN_UUID)
    private String uuid;
    private String sourceOrderUuid;
    private String sourceRollUuid;
    private ProcessRollDispositionAction actionType;
    private ProcessRollDispositionStatus status;
    private String targetOrderUuid;
    private String targetRollUuid;
    private String targetFinishUuid;
    /** JSON array of every finish UUID generated by a multi-piece direct ship. */
    private String targetFinishUuids;
    private String requestId;
    private String reason;
    private String operator;
    private LocalDateTime operateTime;
    private Integer sourceOrderVersion;
    private Integer sourceRollVersion;
}
