import { expect, test } from '@playwright/test'
import { signIn } from './auth'

test('test 环境单卷复卷真实链路探测', async ({ page }, testInfo) => {
  test.setTimeout(180_000)
  await signIn(page)
  const suffix = Date.now().toString().slice(-6)
  await page.goto(`/process-orders/create?fresh=${Date.now()}`)
  await page.waitForLoadState('domcontentloaded')
  await page.waitForTimeout(1200)
  await page.locator('.ant-select').filter({ hasText: '选择客户' }).click()
  await chooseVisibleOption(page, 'E2E打印走查客户-20260812')
  await page.locator('.ant-select').nth(1).click()
  await chooseVisibleOption(page, 'E2E打印走查仓-20260812')
  await page.getByRole('button', { name: '下一步：原纸录入' }).click()
  await page.waitForTimeout(1000)
  await page.getByLabel('母卷 1 品名').fill(`单卷复卷测试-${suffix}`)
  await page.getByLabel('母卷 1 母卷号').fill(`SINGLE-${suffix}`)
  await page.getByRole('button', { name: '下一步：加工方式' }).click()
  await page.waitForTimeout(1000)
  await page.getByLabel('当前母卷主工艺').getByText('复卷', { exact: true }).click()
  await page.getByRole('button', { name: '下一步：工艺配置' }).click()
  await page.waitForTimeout(1800)
  console.log(`[single-config] ${(await page.getByRole('main').innerText()).slice(0, 2600)}`)
  await page.getByLabel('分段 1 目标卷径').fill('40')
  await page.getByLabel('分段 1 成品纸芯').fill('3')
  await page.locator('.process-workspace__preview-trigger').click()
  await expect(page.getByRole('dialog', { name: '后端预览' })).toBeVisible()
  await page.getByRole('button', { name: '刷新预览' }).click()
  await page.waitForTimeout(1500)
  await page.screenshot({ path: testInfo.outputPath('single-config-preview.png'), fullPage: true })
  console.log(`[single-preview] ${(await page.getByRole('dialog', { name: '后端预览' }).innerText()).slice(0, 3000)}`)
  await page.getByRole('dialog', { name: '后端预览' }).getByRole('button', { name: '关闭' }).click().catch(() => undefined)
  await page.getByRole('button', { name: '保存本卷加工方案' }).click()
  await page.waitForTimeout(1800)
  console.log(`[single-after-save] ${(await page.getByRole('main').innerText()).slice(-1800)}`)
  await page.getByRole('button', { name: /下一步：预览确认|保存待处理方案并继续/ }).click()
  await page.waitForTimeout(1800)
  console.log(`[single-preview-step] ${(await page.getByRole('main').innerText()).slice(-3500)}`)
  const submit = page.getByRole('button', { name: '提交并生成真实卷号' })
  console.log(`[single-submit] disabled=${await submit.isDisabled()}`)
  await submit.click()
  await page.waitForTimeout(2200)
  console.log(`[single-submit-result] url=${page.url()} text=${(await page.getByRole('main').innerText()).slice(-2600)}`)
})

async function chooseVisibleOption(page: import('@playwright/test').Page, text: string) {
  const option = page.locator('.ant-select-dropdown:visible .ant-select-item-option').filter({ hasText: text })
  await option.first().click({ timeout: 5_000 })
}
