import { test } from '@playwright/test'
import { signIn } from './auth'

test('test 环境业务链路探测', async ({ page }) => {
  test.setTimeout(180_000)
  await signIn(page)
  await page.goto(`/process-orders/create?fresh=${Date.now()}`)
  await page.waitForLoadState('domcontentloaded')
  await page.waitForTimeout(1500)
  const selects = page.locator('.ant-select')
  console.log(`[flow-select-count] ${await selects.count()}`)
  console.log(`[flow-buttons] ${JSON.stringify(await page.locator('button').allTextContents())}`)
  await selects.filter({ hasText: '选择客户' }).click()
  await page.waitForTimeout(300)
  console.log(`[flow-customer-options] ${JSON.stringify(await page.locator('.ant-select-item-option-content').allTextContents())}`)
  await page.locator('.ant-select-dropdown:visible .ant-select-item-option').first().click({ timeout: 5_000 })
  await selects.nth(1).click()
  await page.waitForTimeout(300)
  console.log(`[flow-warehouse-options] ${JSON.stringify(await page.locator('.ant-select-item-option-content').allTextContents())}`)
  await page.locator('.ant-select-dropdown:visible .ant-select-item-option').filter({ hasText: 'E2E打印走查仓-20260812' }).click({ timeout: 5_000 })
  await page.getByRole('button', { name: '下一步：原纸录入' }).click()
  await page.waitForTimeout(1200)
  console.log(`[flow-roll-buttons] ${JSON.stringify(await page.locator('button').allTextContents())}`)
  console.log(`[flow-roll-inputs] ${JSON.stringify(await page.locator('input').evaluateAll((nodes) => nodes.map((node) => ({ aria: node.getAttribute('aria-label'), placeholder: node.getAttribute('placeholder'), value: node.getAttribute('value') }))))}`)
  const suffix = Date.now().toString().slice(-6)
  await page.getByRole('button', { name: '添加原纸' }).click()
  await page.getByRole('button', { name: '添加原纸' }).click()
  for (let index = 1; index <= 3; index += 1) {
    await page.getByLabel(`母卷 ${index} 品名`).fill(`测试原纸-${suffix}`)
    await page.getByLabel(`母卷 ${index} 母卷号`).fill(`AUDIT-${suffix}-${index}`)
  }
  await page.getByRole('button', { name: '下一步：加工方式' }).click()
  await page.waitForTimeout(1500)
  console.log(`[flow-mode-text] ${(await page.getByRole('main').innerText()).slice(0, 3000)}`)
  console.log(`[flow-mode-selects] ${JSON.stringify(await page.locator('input, [role="radiogroup"], .ant-segmented, button').evaluateAll((nodes) => nodes.map((node) => ({ aria: node.getAttribute('aria-label'), text: node.textContent?.trim(), value: node.getAttribute('value') })).filter((item) => item.aria || item.text)))}`)
  await page.getByRole('button', { name: '批量设置' }).click()
  console.log(`[flow-mode-checkboxes] ${JSON.stringify(await page.locator('input[type="checkbox"]').evaluateAll((nodes) => nodes.map((node) => ({ aria: node.getAttribute('aria-label'), checked: (node as HTMLInputElement).checked }))))}`)
  await page.getByLabel('当前母卷主工艺').getByText('复卷', { exact: true }).click()
  await page.getByLabel('选择母卷 2').check()
  await page.getByLabel('选择母卷 3').check()
  await page.getByRole('button', { name: '应用到已选 2 卷' }).click()
  await page.waitForTimeout(600)
  console.log(`[flow-mode-after-batch] ${(await page.getByRole('main').innerText()).slice(0, 1600)}`)
  await page.getByRole('button', { name: '下一步：工艺配置' }).click()
  await page.waitForTimeout(2200)
  console.log(`[flow-config-text] ${(await page.getByRole('main').innerText()).slice(0, 5000)}`)
  await page.locator('.ant-select-selection-item').filter({ hasText: '改直径' }).click({ timeout: 5_000 })
  await page.waitForTimeout(300)
  console.log(`[flow-rewind-modes] ${JSON.stringify(await page.locator('.ant-select-dropdown:visible .ant-select-item-option-content').allTextContents())}`)
  await page.locator('.ant-select-dropdown:visible .ant-select-item-option').filter({ hasText: '多母卷合并' }).click()
  console.log(`[flow-source-count] ${await page.locator('input[placeholder="选择来源母卷"]').count()}`)
  console.log(`[flow-rewind-segments] ${await page.locator('.rewind-segment').count()}`)
  console.log(`[flow-rewind-editor-text] ${(await page.locator('.rewind-editor').innerText().catch(() => 'none')).slice(0, 3000)}`)
  await page.locator('.process-workspace__pane--main .process-workspace__pane-body').evaluate((node) => {
    node.scrollTop = node.scrollHeight
  })
  await page.waitForTimeout(300)
  console.log(`[flow-source-selects] ${await page.locator('.rewind-editor .ant-select').count()}`)
  console.log(`[flow-source-select-html] ${JSON.stringify(await page.locator('.rewind-editor .ant-select').evaluateAll((nodes) => nodes.map((node) => ({ text: node.textContent?.trim(), aria: node.getAttribute('aria-label'), html: node.outerHTML.slice(0, 500) }))))}`)
  await page.locator('.rewind-editor .ant-select').last().click({ timeout: 5_000, force: true })
  await page.waitForTimeout(300)
  console.log(`[flow-source-options] ${JSON.stringify(await page.locator('.ant-select-dropdown:visible .ant-select-item-option-content').allTextContents())}`)
})
