CREATE TABLE IF NOT EXISTS `sys_dict_item` (
  `uuid` varchar(36) NOT NULL,
  `dict_type` varchar(50) NOT NULL COMMENT '字典分类编码',
  `dict_name` varchar(80) NOT NULL COMMENT '字典分类名称',
  `item_code` varchar(50) NOT NULL COMMENT '字典项编码',
  `item_name` varchar(80) NOT NULL COMMENT '字典项名称',
  `item_value` int DEFAULT NULL COMMENT '兼容业务旧枚举值',
  `sort_no` int NOT NULL DEFAULT 100 COMMENT '排序号',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态 1启用 0停用',
  `built_in` tinyint NOT NULL DEFAULT 0 COMMENT '是否内置 1是 0否',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `create_by` varchar(50) DEFAULT NULL,
  `update_by` varchar(50) DEFAULT NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` int NOT NULL DEFAULT 1,
  `ext_str1` varchar(255) DEFAULT NULL,
  `ext_str2` varchar(255) DEFAULT NULL,
  `ext_num1` decimal(12,3) DEFAULT NULL,
  `ext_num2` decimal(12,3) DEFAULT NULL,
  PRIMARY KEY (`uuid`),
  UNIQUE KEY `uk_sys_dict_item_code` (`dict_type`, `item_code`, `is_deleted`),
  KEY `idx_sys_dict_item_type` (`dict_type`),
  KEY `idx_sys_dict_item_status` (`status`),
  KEY `idx_is_deleted` (`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统数据字典项';

CREATE TABLE IF NOT EXISTS `sys_config_item` (
  `uuid` varchar(36) NOT NULL,
  `config_group` varchar(50) NOT NULL COMMENT '参数分组',
  `config_key` varchar(80) NOT NULL COMMENT '参数键',
  `config_name` varchar(80) NOT NULL COMMENT '参数名称',
  `config_value` varchar(255) NOT NULL COMMENT '参数值',
  `value_type` varchar(20) NOT NULL DEFAULT 'string' COMMENT '值类型 string/number/boolean',
  `unit` varchar(20) DEFAULT NULL COMMENT '单位',
  `sort_no` int NOT NULL DEFAULT 100 COMMENT '排序号',
  `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态 1启用 0停用',
  `built_in` tinyint NOT NULL DEFAULT 0 COMMENT '是否内置 1是 0否',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `is_deleted` tinyint NOT NULL DEFAULT 0,
  `create_by` varchar(50) DEFAULT NULL,
  `update_by` varchar(50) DEFAULT NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` int NOT NULL DEFAULT 1,
  `ext_str1` varchar(255) DEFAULT NULL,
  `ext_str2` varchar(255) DEFAULT NULL,
  `ext_num1` decimal(12,3) DEFAULT NULL,
  `ext_num2` decimal(12,3) DEFAULT NULL,
  PRIMARY KEY (`uuid`),
  UNIQUE KEY `uk_sys_config_key` (`config_key`, `is_deleted`),
  KEY `idx_sys_config_group` (`config_group`),
  KEY `idx_sys_config_status` (`status`),
  KEY `idx_is_deleted` (`is_deleted`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统参数配置';
