SET SESSION lock_wait_timeout = 5;

CREATE TABLE `sys_export_task` (
  `uuid` VARCHAR(36) NOT NULL,
  `request_id` VARCHAR(64) NOT NULL,
  `task_type` VARCHAR(30) NOT NULL,
  `task_name` VARCHAR(120) NOT NULL,
  `source_uuid` VARCHAR(36) NOT NULL,
  `requester_uuid` VARCHAR(36) NOT NULL,
  `requester_name` VARCHAR(50) NOT NULL,
  `task_status` TINYINT NOT NULL DEFAULT 1 COMMENT '1等待 2执行中 3成功 4失败',
  `progress` TINYINT NOT NULL DEFAULT 0,
  `file_name` VARCHAR(255) DEFAULT NULL,
  `file_path` VARCHAR(500) DEFAULT NULL,
  `file_size` BIGINT DEFAULT NULL,
  `error_message` VARCHAR(500) DEFAULT NULL,
  `started_at` DATETIME DEFAULT NULL,
  `completed_at` DATETIME DEFAULT NULL,
  `acknowledged_at` DATETIME DEFAULT NULL,
  `expires_at` DATETIME NOT NULL,
  `is_deleted` TINYINT NOT NULL DEFAULT 0,
  `create_by` VARCHAR(50) DEFAULT NULL,
  `update_by` VARCHAR(50) DEFAULT NULL,
  `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `version` INT NOT NULL DEFAULT 1,
  `ext_str1` VARCHAR(255) DEFAULT NULL,
  `ext_str2` VARCHAR(255) DEFAULT NULL,
  `ext_num1` DECIMAL(12,3) DEFAULT NULL,
  `ext_num2` DECIMAL(12,3) DEFAULT NULL,
  PRIMARY KEY (`uuid`),
  UNIQUE KEY `uk_export_task_request` (`requester_uuid`, `request_id`),
  KEY `idx_export_task_owner_time` (`requester_uuid`, `create_time`, `uuid`),
  KEY `idx_export_task_owner_status` (`requester_uuid`, `task_status`, `acknowledged_at`),
  KEY `idx_export_task_expiry` (`expires_at`, `task_status`),
  CONSTRAINT `chk_export_task_status` CHECK (`task_status` BETWEEN 1 AND 4),
  CONSTRAINT `chk_export_task_progress` CHECK (`progress` BETWEEN 0 AND 100)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='异步导出任务中心';
